config/routes.rb
Rails.application.routes.draw do
  get 'admin/pending'

  get 'admin/disapproved'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :menus
  resources :items
  resources :admin
  post '/items/:id/upload' => 'items#upload_picture', as: 'image_upload'
  get '/items/:id/first_image' => 'items#serve_first_image'
  post '/images/:id/approve' => 'images#approve', as: 'image_approve'
  post '/images/:id/disapprove' => 'images#disapprove', as: 'image_disapprove'
  get '/pending' => 'admin#pending'
  get '/disapproved' => 'admin#disapproved'
  get '/adminuser' => 'admin#adminuser'
  post '/items/:id/add_to_preferences' => 'items#add_to_preferences', as: 'add_to_preferences'
  post '/items/:id/remove_from_preferences' => 'items#remove_from_preferences', as: 'remove_from_preferences'
  put '/admin/:id' => 'admin#update', as: 'update'
  root 'menus#index'
  %w( 403 404 422 500 503).each do |code|
    get code, :to => 'errors#show', :code => code
  end

end

app/views/admin/adminuser.html.haml
.container
	.section
		.subheader Admin Users
		- @admin.each do |admin|
			.list-item.clear
				.list-content
					= admin.email
				.list-button 
					= button_to 'Make regular user', update_path(admin.id), {:method => :put, :class => 'list-btn'}
			.list-hr
	.section
		.subheader Regular Users
		- @nonadmin.each do |nonadmin|
			.list-item.clear
				.list-content
					= nonadmin.email
				.list-button
					= button_to 'Make admin', update_path(nonadmin.id), {:method => :put, :class => 'list-btn'}
			.list-hr

app/views/admin/disapproved.html.haml
.container
  .header Disapproved Images
.items-container.clear
  - if @disapproved_images.empty?
    #error_explanation
      %h2
        = "No disapproved images available."
  - else
    - @disapproved_images.each do |image|
      .item-container
        .item-content-container
          .item-icons-container.clear
            = link_to image_approve_path(image.id), :method => :post  do
              .status-container.approve-container#full
                Approve
                %i.fa.fa-check{"aria-hidden" => "true"}
          .item-image-container
            = image_tag image.filename, {:class => 'img_scaled_wh'}
          .item-text-container
            .item-text
              = image.item.name

app/views/admin/pending.html.haml
.container
  .header Pending Images
.items-container.clear
  - if @pending_images.empty?
    #error_explanation
      %h2
        = "No pending images. You're all caught up! "
  - else
    - @pending_images.each do |image|
      .item-container
        .item-content-container
          .item-icons-container.clear
            = link_to image_approve_path(image.id), :method => :post  do
              .status-container.approve-container.left
                Approve
                %i.fa.fa-check{"aria-hidden" => "true"}
            = link_to image_disapprove_path(image.id), :method => :post do
              .status-container.disapprove-container.right
                Disapprove
                %i.fa.fa-times{"aria-hidden" => "true"} 
          .item-image-container
            = image_tag image.filename, {:class => 'img_scaled_wh'}
          .item-text-container
            .item-text
              = image.item.name