config/routes.rb
Rails.application.routes.draw do
  get 'admin/pending'

  get 'admin/disapproved'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :menus
  resources :items
  resources :admin
  post '/items/:id/upload' => 'items#upload_picture', as: 'image_upload'
  get '/items/:id/first_image' => 'items#serve_first_image'
  post '/images/:id/approve' => 'images#approve', as: 'image_approve'
  post '/images/:id/disapprove' => 'images#disapprove', as: 'image_disapprove'
  get '/pending' => 'admin#pending'
  get '/disapproved' => 'admin#disapproved'
  get '/adminuser' => 'admin#adminuser'
  post '/items/:id/add_to_preferences' => 'items#add_to_preferences', as: 'add_to_preferences'
  post '/items/:id/remove_from_preferences' => 'items#remove_from_preferences', as: 'remove_from_preferences'
  put '/admin/:id' => 'admin#update', as: 'update'
  root 'menus#index'
  %w( 403 404 422 500 503).each do |code|
    get code, :to => 'errors#show', :code => code
  end

end

app/views/shared/_navbar.html.haml
.navbar-container.clear
  .container
    .navbar-content-container.left.clear
      #logo.left
        %a{:href => menus_path}
          %i.fa.fa-cutlery{"aria-hidden" => "true"}
      - if user_signed_in? && current_user.admin?
        .navbar-item.left
          = link_to 'Pending', pending_path
        .navbar-item.left
          = link_to 'Disapproved', disapproved_path
        .navbar-item.left
          = link_to 'Adminusers', adminuser_path
    .navbar-content-container.right
      - if user_signed_in?
        .dropdown
          .navbar-item
            = current_user.email
            %i.fa.fa-caret-down{"aria-hidden" => "true"}
          .dropdown-content
            = link_to 'My account', edit_user_registration_path, {:class => 'navbar-item'} 
            = link_to'Sign out', destroy_user_session_path, {:method => :delete, :class => 'navbar-item'}

      - else
        .right.clear
          .navbar-item.left
            = link_to "Signin", new_user_session_path
          .navbar-item.left
            = link_to "Sign up", new_user_registration_path

app/views/shared/_selection.html.haml
= form_tag menus_path, {:method => :get, id: "menus_form", class: "clear"} do
  .radios.location
    - @locations.each do |location|
      = radio_button_tag :location, "#{location}", @selected_location == location, :id => "#{location.tr(' ','_')}", :class => 'radio'
      = label_tag location, location.titleize, class: 'radio'
  .radios.meal
    - @meals.each do |meal|
      = radio_button_tag :meal, "#{meal}", @selected_meal == meal, :id => "#{meal.tr('/','_')}", :class => 'radio'
      = label_tag meal, meal.titleize, class: 'radio'
  = submit_tag 'Submit', id: "menus-submit", class: 'radio'