config/routes.rb
Rails.application.routes.draw do
  get 'admin/pending'

  get 'admin/disapproved'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :menus
  resources :items
  resources :admin
  post '/items/:id/upload' => 'items#upload_picture', as: 'image_upload'
  get '/items/:id/first_image' => 'items#serve_first_image'
  post '/images/:id/approve' => 'images#approve', as: 'image_approve'
  post '/images/:id/disapprove' => 'images#disapprove', as: 'image_disapprove'
  get '/pending' => 'admin#pending'
  get '/disapproved' => 'admin#disapproved'
  get '/adminuser' => 'admin#adminuser'
  post '/items/:id/add_to_preferences' => 'items#add_to_preferences', as: 'add_to_preferences'
  post '/items/:id/remove_from_preferences' => 'items#remove_from_preferences', as: 'remove_from_preferences'
  put '/admin/:id' => 'admin#update', as: 'update'
  root 'menus#index'
  %w( 403 404 422 500 503).each do |code|
    get code, :to => 'errors#show', :code => code
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
    has_and_belongs_to_many :menus, :join_table => :items_menus
    has_and_belongs_to_many :users, :join_table => :items_users
    has_many :images
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:upload_picture, :add_to_preferences, :remove_from_preferences]

  # GET /items/1
  # GET /items/1.json
  def show
    @meal = params[:meal]
    @location = params[:location]
    @menu_id = Menu.where(:meal => @meal, :location => @location).first.id
    @item = Item.where(:id => params[:id]).first
    @images = @item.images.where(state: 1)
    @other_locations = @item.menus.where(:meal => @meal).reject {|menu|  menu.location == @location}
  end

  def upload_picture
    item = Item.where(:id => params[:id]).first
    Image.new(:filename => params[:filename], :state => 0, :item => item, :user => current_user).save
    redirect_to :back
  end
  
  def add_to_preferences
    user = current_user
    item = Item.where(:id => params[:id]).first
    if not user.items.include? (item)
      if user.items.length < 10
        user.items << item
        user.save!
        user.reload
        item.reload
      else
        # some flash message
        flash[:error] = "You can have only 10 favorites"
      end
    end
    redirect_to :back
  end
  
  def remove_from_preferences
    user = current_user
    item = Item.where(:id => params[:id]).first
    if user.items.include? (item)
      user.items.delete(item)
      user.save!
      user.reload
      item.reload
    end
    redirect_to :back
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/show.html.haml
.container
  .header
    #{@item.name}
  .container.clear
    .item-options.left
      .preference-buttons
        - if @item.vegan
          %div
            = image_tag "vegan.png"
        - if @item.vegetarian
          %div
            = image_tag "vegetarian.png"
        - if user_signed_in?
          - if !current_user.items.include? (@item)
            = link_to add_to_preferences_path(@item.id), :method => :post, :class => 'add', :id => @item.name + "item" do
              %i.fa.fa-heart-o{"aria-hidden" => "true"}
          - else
            = link_to remove_from_preferences_path(@item.id), :method => :post, :class => 'remove', :id => @item.name + "item" do
              %i.fa.fa-heart{"aria-hidden" => "true"}
    .upload-container.right
      - if user_signed_in?
        #upload-button.clear
          .upload-text.left
            %i.fa.fa-camera{"aria-hidden" => "true"}
            Add an image
  .container
    .availability
      Available for #{@meal} at #{@location}

.container
  - if not @images.empty?
    .items-container.clear
      - @images.each do |image|
        .item-container.item-content-container
          - if user_signed_in? && current_user.admin?
            .item-icons-container.clear
              = link_to image_disapprove_path(image.id), :method => :post do
                .status-container.disapprove-container#full
                  Remove
                  %i.fa.fa-times{"aria-hidden" => "true"}
          .item-image-container
            = image_tag image.filename, class: 'img_scaled_wh'
  .container
    .nutrition-container
      - if @item.nutrition_available
        .nutrition-facts-container
          .subheader Nutrition Facts
          .container.clear
            .half
              %ul
                %li
                  Calories:
                  %span #{@item.calories}
                %li
                  Total Fat:
                  %span #{@item.total_fat}
                %li
                  Cholesterol:
                  %span #{@item.cholesterol}
                %li
                  Sodium:
                  %span #{@item.sodium}
            .half
              %ul
                %li
                  Dietary Fiber:
                  %span #{@item.dietary_fiber}
                - if not @item.vitamin_c_percent.nil?
                  %li
                    Vitamin C:
                    %span #{@item.vitamin_c_percent + '%'}
                %li
                  Allergens:
                  %span #{@item.allergens}
          %hr
        .ingredients-container
          .subheader#ingredients-button Ingredients
          .ingredients-text.hidden #{@item.ingredients}
      - else
        .subheader No nutrition information available
      %hr
      - if not @other_locations.empty?
        .other-location-container.clear
          .subtitle.pretext.left Also available for #{@meal} at
          .other-location-item-container.left.clear
            - @other_locations.each do |location|
              .other-location-item.left
                = link_to location.location, menu_path(location.id)

= javascript_tag do
  var filepicker_key = "#{ENV['FILEPICKER_KEY']}";
  var upload_post_url = "#{image_upload_path(@item.id)}";